### ISSUE TITLE
No module named 'parched'

### ISSUE THREAD

**Issue by Uroc327** [onny/pkgcheck#1]
Apparently `parched-git` only installs modules for python 2.7.
`pkgcheck` uses `python3`, which does not get the modules via the `parched-git` package.

**Comment by alexdantas** [comment]
I'm a total noob with Python, but just installed all of the specified dependencies (`yaourt -S parched-git python3-aur python-requests python-xdg`) and everything ran up fine.

Is that because something specific to my machine or was this issue solved with time?

**Comment by Uroc327** [comment]
Hmm.. Interesting! I have them installed (and u2d), too, but it still isn't able to find parched.
